### ISSUE TITLE
v1 Roadmap

### ISSUE THREAD

**Issue by LEAFERx** [LEAFERx/hexo-leancloud-counter#3]
# High Priority
- [x] <del>Integrate hookguard</del> see [hexo-leancloud-counter-hookguard](https://github.com/theme-next/hexo-leancloud-counter-hookguard) and [hookguard setup doc](https://theme-next.github.io/hexo-leancloud-counter/#add-hookguard-to-application).
- [ ] Refactor deployer
- [x] Refactor on-page script
  - [x] Get rid of jquery
  - [x] Refactor selection
  - [x] Expose APIs
  - [x] Reduce bundled script size
- [ ] Finish document

# Others
- [ ] Hot post feature
- [ ] Integrate CI
- [ ] Unit test
- [ ] Post count manager
- [ ] More CLI commands
- [ ] Pre-render templates
